version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vinaside-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27020:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: vinaside-redis
    ports:
      - 6380:6379
    restart: unless-stopped

  file-server:
    image: node:22
    container_name: file-server
    working_dir: /app
    volumes:
      - ./uploads:/app/uploads
      - ./server.js:/app/server.js
    ports:
      - 3000:3000
    command: >
      sh -c "npm install express multer && node server.js"
    restart: unless-stopped

volumes:
  mongodb_data_container:
