version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vinaside-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27020:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: vinaside-redis
    ports:
      - 6380:6379
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: vinaside-backend
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vinaside-frontend
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
